name: nostra
description: "Nostra project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  drop_shadow_image: ^0.9.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.2
  fluttertoast: ^8.2.10
  google_fonts: ^4.0.3
  go_router: ^14.6.2
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/HomeSliderPicture_1.jpg
    - assets/images/HomeSliderPicture_2.jpg
    - assets/images/HomeSliderPicture_3.jpg
    - assets/images/HomeSliderPicture_4.jpg
    - assets/images/HomeSliderPicture_5.jpg
    - assets/images/HomeBackgroundPicture_1.png
    - assets/profile/

  fonts:
    - family: AcmeRegular
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
    - family: BebasNeueRegular
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: ConcertOneRegular
      fonts:
        - asset: assets/fonts/ConcertOne-Regular.ttf
    - family: PatuaOneRegular
      fonts:
        - asset: assets/fonts/PatuaOne-Regular.ttf
    - family: PermanentMarkereRegular
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
    - family: RubikMonoOneRegular
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf
    - family: ChewyRegular
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf